name: Issue Close Require

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: need reproduce
        uses: actions-cool/issues-helper@v1.7
        with:
          actions: 'close-issues'
          labels: '🤔 Need Reproduce'
          inactive-day: 7
          body: |
            Since the issue was labeled with `Need Reproduce`, but no response in 7 days. This issue will be closed. If you have any questions, you can comment and reply.

            Since this issue was marked as requiring reproduction information, but no response was received for 7 days. Now closing the issue, if you have any questions, you can comment and reply.
